// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    paths: {
      "icg": "public/scripts"
    },
    waitSeconds: 10,
    AMDLoaderConfiguration: {}
  });

  require([
    "icg/sample"
  ], function(){
    // no need to do anything here.  we are simply using this to bootstrap the prune.


  });

}).call(this);
